CREATE DATABASE CarSalesStore;
GO

USE CarSalesStore;
GO

CREATE TABLE Cars (
	CarId INT PRIMARY KEY IDENTITY(1,1),
	Brand NVARCHAR(50) NOT NULL,
	Model NVARCHAR(50) NOT NULL,
	Price DECIMAL(18, 2) NOT NULL,
	Stock INT NOT NULL
);
GO

CREATE TABLE Customers (
	CustomerId INT PRIMARY KEY IDENTITY(1,1),
	FirstName NVARCHAR(50) NOT NULL,
	LastName NVARCHAR(50) NOT NULL,
	Email NVARCHAR(100) NOT NULL UNIQUE,
);
GO

CREATE TABLE Sales (
	SaleId INT PRIMARY KEY IDENTITY(1,1),
	CarId INT NOT NULL,
	CustomerId INT NOT NULL,
	SaleDate DATETIME NOT NULL DEFAULT GETDATE(),
	FOREIGN KEY (CarId) REFERENCES Cars(CarId),
	FOREIGN KEY (CustomerId) REFERENCES Customers(CustomerId)
);